# Generated by Django 3.0.5 on 2020-04-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tno', models.IntegerField()),
                ('tname', models.CharField(max_length=64)),
                ('tsal', models.FloatField()),
                ('taddr', models.CharField(max_length=64)),
            ],
        ),
    ]
